import 'bootstrap/dist/css/bootstrap.min.css';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { AuthContextProvider } from '@/context/AuthContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>        <AuthContextProvider>
          <Navigation />
          {children}
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
